import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// PUBLIC_INTERFACE
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /**
   * Root layout: Defines top-level structure, navigation, and shared styles.
   */
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <nav aria-label="Primary" className="site-nav">
            <ul
              style={{
                display: "flex",
                gap: "2rem",
                listStyle: "none",
                padding: 0,
                margin: 0,
                alignItems: "center",
                fontWeight: 500,
                fontSize: "1rem",
              }}
            >
              <li style={{ fontWeight: 700, fontSize: "1.08em" }}>
                <Link href="/">
                  <span style={{ color: "#22223b" }}>ARCHITECT PORTFOLIO</span>
                </Link>
              </li>
              <li>
                <Link href="/about">About Me</Link>
              </li>
              <li>
                <Link href="/projects">Projects</Link>
              </li>
              <li>
                <Link href="/skills">Skills</Link>
              </li>
              <li>
                <Link href="/contact">Contact</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main style={{ maxWidth: 900, margin: "0 auto", padding: "2rem 1rem" }}>
          {children}
        </main>
      </body>
    </html>
  );
}
